server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        web-flux:
          routes:
            - id: user-service
              uri: http://user-service:8083
              predicates:
                - Path=/users/**
              filters:
                - PrefixPath=/api

            - id: product-service
              uri: http://product-service:8081
              predicates:
                - Path=/products/**
              filters:
                - PrefixPath=/api

            - id: order-service
              uri: http://order-service:8082
              predicates:
                - Path=/orders/**
              filters:
                - PrefixPath=/api

